// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        upgrade => upgrade
        setEarner => set_earner
        removeEarner => remove_earner
        getEarnersInfo => get_earners_info
        earners => earners
        earnerName => earner_name
        earnerPercentage => earner_percentage
        earnersTotalPercentage => earners_total_percentage
        sendFees => send_fees
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
