// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    earners
    (
        init => init
        upgrade => upgrade
        addAdmins => add_admin
        removeAdmins => remove_admin
        isAdmin => is_admin
        getAdmins => admins
        pause => pause
        unpause => unpause
        isPaused => is_paused
        distribute => distribute
        setEarners => set_earner
        removeEarners => remove_earner
        getEarners => get_earners_info
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
